# Generated by Django 4.2.30 on 2026-08-24 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_bill_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='bill',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
