services:
  - type: web
    name: krishna-tailor-backend
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn tailor_shop.wsgi:application --log-file -"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHON_VERSION
        value: "3.13.0"
